---
mqtt:
    # Specify your MQTT Broker's hostname or IP address here
    host: localhost
    # Preface for the topics $PREFACE/$USER_NAME/motion
    preface: camera

# Port number to listen on
port: 8021
